ADD_SCENE(metroflip, start, Start)
ADD_SCENE(metroflip, ravkav, RavKav)
ADD_SCENE(metroflip, charliecard, CharlieCard)
ADD_SCENE(metroflip, metromoney, Metromoney)
ADD_SCENE(metroflip, read_success, ReadSuccess)
ADD_SCENE(metroflip, bip, Bip)
ADD_SCENE(metroflip, about, About)
ADD_SCENE(metroflip, credits, Credits)
