ADD_SCENE(metroflip, start, Start)
ADD_SCENE(metroflip, auto, Auto)
ADD_SCENE(metroflip, parse, Parse)
ADD_SCENE(metroflip, ovc, OVC)
ADD_SCENE(metroflip, about, About)
ADD_SCENE(metroflip, credits, Credits)
